In [29]:
import pandas as pd
import numpy as np

In [30]:
# read dataset
data = pd.read_csv('../data/raw/AmesHousing.csv')
data.head()

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [31]:
col_obj = data.select_dtypes(include='object').columns
col_obj.to_list()

['MS Zoning',
 'Street',
 'Alley',
 'Lot Shape',
 'Land Contour',
 'Utilities',
 'Lot Config',
 'Land Slope',
 'Neighborhood',
 'Condition 1',
 'Condition 2',
 'Bldg Type',
 'House Style',
 'Roof Style',
 'Roof Matl',
 'Exterior 1st',
 'Exterior 2nd',
 'Mas Vnr Type',
 'Exter Qual',
 'Exter Cond',
 'Foundation',
 'Bsmt Qual',
 'Bsmt Cond',
 'Bsmt Exposure',
 'BsmtFin Type 1',
 'BsmtFin Type 2',
 'Heating',
 'Heating QC',
 'Central Air',
 'Electrical',
 'Kitchen Qual',
 'Functional',
 'Fireplace Qu',
 'Garage Type',
 'Garage Finish',
 'Garage Qual',
 'Garage Cond',
 'Paved Drive',
 'Pool QC',
 'Fence',
 'Misc Feature',
 'Sale Type',
 'Sale Condition']

In [32]:
data[col_obj]

,MS Zoning,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,...,Garage Type,Garage Finish,Garage Qual,Garage Cond,Paved Drive,Pool QC,Fence,Misc Feature,Sale Type,Sale Condition
0,RL,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,...,Attchd,Fin,TA,TA,P,NaN,NaN,NaN,WD,Normal
1,RH,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,...,Attchd,Unf,TA,TA,Y,NaN,MnPrv,NaN,WD,Normal
2,RL,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,...,Attchd,Unf,TA,TA,Y,NaN,NaN,Gar2,WD,Normal
3,RL,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,NAmes,Norm,...,Attchd,Fin,TA,TA,Y,NaN,NaN,NaN,WD,Normal
4,RL,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,...,Attchd,Fin,TA,TA,Y,NaN,MnPrv,NaN,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,RL,Pave,NaN,IR1,Lvl,AllPub,CulDSac,Gtl,Mitchel,Norm,...,Detchd,Unf,TA,TA,Y,NaN,GdPrv,NaN,WD,Normal
2926,RL,Pave,NaN,IR1,Low,AllPub,Inside,Mod,Mitchel,Norm,...,Attchd,Unf,TA,TA,Y,NaN,MnPrv,NaN,WD,Normal
2927,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Mitchel,Norm,...,NaN,NaN,NaN,NaN,Y,NaN,MnPrv,Shed,WD,Normal
2928,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Mod,Mitchel,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
2929,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Mod,Mitchel,Norm,...,Attchd,Fin,TA,TA,Y,NaN,NaN,NaN,WD,Normal

In [142]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

def load_data(cleaned_file_path):
    data = pd.read_csv(cleaned_file_path)
    print(f"data loaded for scaling. {data.shape[0]} rows and {data.shape[1]} columns loaded")
    return data

In [34]:
def scaling_num(X_dataFrame:pd.DataFrame):
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_dataFrame)
    return X_scaled

In [35]:
def one_hot_encode_cat(X_dataFrame:pd.DataFrame):
    encode_cat = pd.get_dummies(X_dataFrame)
    return encode_cat

In [36]:
def save_data(dataFrame:pd.DataFrame, dest_file_path):
    dataFrame.to_csv(dest_file_path, index=False)
    print(f"Datafrmae saved to {dest_file_path}")

In [37]:
def runScaling_features(dataFrame:pd.DataFrame, pred_cols_df:pd.DataFrame):
    # making X and y from the dataset
    X = dataFrame.drop(columns=pred_cols_df.columns)
    y = pred_cols_df

    # scaling number columns
    X = scaling_num(X)

    # # scaling categorical columns
    # X = one_hot_encode_cat(X)

    # df = X.merge(y)

    # df.to_csv("data/precessed/Cleaned_Scaled_AmesHousing.csv")

In [143]:
from_path = "../data/processed/Clean_AmesHousing.csv"
data = load_data(cleaned_file_path= from_path)

data loaded for scaling. 5860 rows and 79 columns loaded

In [80]:
pred_cols_df=data[['SalePrice']]
pred_cols_df.head()

   SalePrice
0   215000.0
1   105000.0
2   172000.0
3   244000.0
4   189900.0

In [95]:
X=data.drop(columns=pred_cols_df.columns)
X

,Order,PID,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,...,Functional,Fireplace Qu,Garage Type,Garage Finish,Garage Qual,Garage Cond,Paved Drive,Fence,Sale Type,Sale Condition
0,1.0,526301100.0,20.0,141.0,31770.0,6.0,5.0,1960.0,1960.0,112.0,...,Typ,Gd,Attchd,Unf,TA,TA,Y,MnPrv,WD,Normal
1,2.0,526350040.0,20.0,80.0,11622.0,5.0,6.0,1961.0,1961.0,0.0,...,Typ,Gd,Attchd,Unf,TA,TA,Y,MnPrv,WD,Normal
2,3.0,526351010.0,20.0,81.0,14267.0,6.0,6.0,1958.0,1958.0,108.0,...,Typ,Gd,Attchd,Unf,TA,TA,Y,MnPrv,WD,Normal
3,4.0,526353030.0,20.0,93.0,11160.0,7.0,5.0,1968.0,1968.0,0.0,...,Typ,Gd,Attchd,Unf,TA,TA,Y,MnPrv,WD,Normal
4,5.0,527105010.0,60.0,74.0,13830.0,5.0,5.0,1997.0,1998.0,0.0,...,Typ,Gd,Attchd,Unf,TA,TA,Y,MnPrv,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5855,1465.5,535453620.0,50.0,68.0,9436.5,6.0,5.0,1973.0,1993.0,0.0,...,Typ,Gd,Detchd,Unf,TA,TA,Y,GdPrv,WD,Normal
5856,1465.5,535453620.0,50.0,68.0,9436.5,6.0,5.0,1973.0,1993.0,0.0,...,Typ,Gd,Attchd,Unf,TA,TA,Y,MnPrv,WD,Normal
5857,1465.5,535453620.0,50.0,68.0,9436.5,6.0,5.0,1973.0,1993.0,0.0,...,Typ,Gd,Attchd,Unf,TA,TA,Y,MnPrv,WD,Normal
5858,1465.5,535453620.0,50.0,68.0,9436.5,6.0,5.0,1973.0,1993.0,0.0,...,Typ,TA,Attchd,RFn,TA,TA,Y,MnPrv,WD,Normal
5859,1465.5,535453620.0,50.0,68.0,9436.5,6.0,5.0,1973.0,1993.0,0.0,...,Typ,TA,Attchd,Fin,TA,TA,Y,MnPrv,WD,Normal

In [96]:
"SalePrice" in X.columns.to_list()

False

In [97]:
y = pred_cols_df

In [98]:
X = one_hot_encode_cat(X)

In [99]:
type(X)

pandas.core.frame.DataFrame

In [100]:
X

,Order,PID,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,...,Sale Type_New,Sale Type_Oth,Sale Type_VWD,Sale Type_WD,Sale Condition_Abnorml,Sale Condition_AdjLand,Sale Condition_Alloca,Sale Condition_Family,Sale Condition_Normal,Sale Condition_Partial
0,1.0,526301100.0,20.0,141.0,31770.0,6.0,5.0,1960.0,1960.0,112.0,...,False,False,False,True,False,False,False,False,True,False
1,2.0,526350040.0,20.0,80.0,11622.0,5.0,6.0,1961.0,1961.0,0.0,...,False,False,False,True,False,False,False,False,True,False
2,3.0,526351010.0,20.0,81.0,14267.0,6.0,6.0,1958.0,1958.0,108.0,...,False,False,False,True,False,False,False,False,True,False
3,4.0,526353030.0,20.0,93.0,11160.0,7.0,5.0,1968.0,1968.0,0.0,...,False,False,False,True,False,False,False,False,True,False
4,5.0,527105010.0,60.0,74.0,13830.0,5.0,5.0,1997.0,1998.0,0.0,...,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5855,1465.5,535453620.0,50.0,68.0,9436.5,6.0,5.0,1973.0,1993.0,0.0,...,False,False,False,True,False,False,False,False,True,False
5856,1465.5,535453620.0,50.0,68.0,9436.5,6.0,5.0,1973.0,1993.0,0.0,...,False,False,False,True,False,False,False,False,True,False
5857,1465.5,535453620.0,50.0,68.0,9436.5,6.0,5.0,1973.0,1993.0,0.0,...,False,False,False,True,False,False,False,False,True,False
5858,1465.5,535453620.0,50.0,68.0,9436.5,6.0,5.0,1973.0,1993.0,0.0,...,False,False,False,True,False,False,False,False,True,False
5859,1465.5,535453620.0,50.0,68.0,9436.5,6.0,5.0,1973.0,1993.0,0.0,...,False,False,False,True,False,False,False,False,True,False

In [101]:
X.dtypes.value_counts()

bool       256
float64     42
Name: count, dtype: int64

In [102]:
X_num= X.select_dtypes(include=['int64', 'float64'])

In [103]:
X_num

,Order,PID,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,...,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,Total SF,Total Bathrooms,bath per bedroom,House Age
0,1.0,526301100.0,20.0,141.0,31770.0,6.0,5.0,1960.0,1960.0,112.0,...,0.0,0.0,0.0,0.0,5.0,2010.0,2736.0,1.0,0.333333,50.0
1,2.0,526350040.0,20.0,80.0,11622.0,5.0,6.0,1961.0,1961.0,0.0,...,0.0,120.0,0.0,0.0,6.0,2010.0,1778.0,1.0,0.500000,49.0
2,3.0,526351010.0,20.0,81.0,14267.0,6.0,6.0,1958.0,1958.0,108.0,...,0.0,0.0,0.0,12500.0,6.0,2010.0,2658.0,1.5,0.500000,52.0
3,4.0,526353030.0,20.0,93.0,11160.0,7.0,5.0,1968.0,1968.0,0.0,...,0.0,0.0,0.0,0.0,4.0,2010.0,4220.0,2.5,0.833333,42.0
4,5.0,527105010.0,60.0,74.0,13830.0,5.0,5.0,1997.0,1998.0,0.0,...,0.0,0.0,0.0,0.0,3.0,2010.0,2557.0,2.5,0.833333,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5855,1465.5,535453620.0,50.0,68.0,9436.5,6.0,5.0,1973.0,1993.0,0.0,...,0.0,0.0,0.0,0.0,6.0,2008.0,2452.0,2.0,0.625000,34.0
5856,1465.5,535453620.0,50.0,68.0,9436.5,6.0,5.0,1973.0,1993.0,0.0,...,0.0,0.0,0.0,0.0,6.0,2008.0,2452.0,2.0,0.625000,34.0
5857,1465.5,535453620.0,50.0,68.0,9436.5,6.0,5.0,1973.0,1993.0,0.0,...,0.0,0.0,0.0,0.0,6.0,2008.0,2452.0,2.0,0.625000,34.0
5858,1465.5,535453620.0,50.0,68.0,9436.5,6.0,5.0,1973.0,1993.0,0.0,...,0.0,0.0,0.0,0.0,6.0,2008.0,2452.0,2.0,0.625000,34.0
5859,1465.5,535453620.0,50.0,68.0,9436.5,6.0,5.0,1973.0,1993.0,0.0,...,0.0,0.0,0.0,0.0,6.0,2008.0,2452.0,2.0,0.625000,34.0

In [104]:
X_num.isna().sum()[X_num.isna().sum()>0]

Series([], dtype: int64)

In [105]:
X_num.columns

Index(['Order', 'PID', 'MS SubClass', 'Lot Frontage', 'Lot Area',
       'Overall Qual', 'Overall Cond', 'Year Built', 'Year Remod/Add',
       'Mas Vnr Area', 'BsmtFin SF 1', 'BsmtFin SF 2', 'Bsmt Unf SF',
       'Total Bsmt SF', '1st Flr SF', '2nd Flr SF', 'Low Qual Fin SF',
       'Gr Liv Area', 'Bsmt Full Bath', 'Bsmt Half Bath', 'Full Bath',
       'Half Bath', 'Bedroom AbvGr', 'Kitchen AbvGr', 'TotRms AbvGrd',
       'Fireplaces', 'Garage Yr Blt', 'Garage Cars', 'Garage Area',
       'Wood Deck SF', 'Open Porch SF', 'Enclosed Porch', '3Ssn Porch',
       'Screen Porch', 'Pool Area', 'Misc Val', 'Mo Sold', 'Yr Sold',
       'Total SF', 'Total Bathrooms', 'bath per bedroom', 'House Age'],
      dtype='object')

In [106]:
X_non_num = X.select_dtypes(exclude=['int64', 'float64'])

In [107]:
type(X_non_num)

pandas.core.frame.DataFrame

In [108]:
X_non_num.columns

Index(['MS Zoning_A (agr)', 'MS Zoning_C (all)', 'MS Zoning_FV',
       'MS Zoning_I (all)', 'MS Zoning_RH', 'MS Zoning_RL', 'MS Zoning_RM',
       'Street_Grvl', 'Street_Pave', 'Lot Shape_IR1',
       ...
       'Sale Type_New', 'Sale Type_Oth', 'Sale Type_VWD', 'Sale Type_WD ',
       'Sale Condition_Abnorml', 'Sale Condition_AdjLand',
       'Sale Condition_Alloca', 'Sale Condition_Family',
       'Sale Condition_Normal', 'Sale Condition_Partial'],
      dtype='object', length=256)

In [112]:
X_non_num = X_non_num.astype('int64')
X_non_num

,MS Zoning_A (agr),MS Zoning_C (all),MS Zoning_FV,MS Zoning_I (all),MS Zoning_RH,MS Zoning_RL,MS Zoning_RM,Street_Grvl,Street_Pave,Lot Shape_IR1,...,Sale Type_New,Sale Type_Oth,Sale Type_VWD,Sale Type_WD,Sale Condition_Abnorml,Sale Condition_AdjLand,Sale Condition_Alloca,Sale Condition_Family,Sale Condition_Normal,Sale Condition_Partial
0,0,0,0,0,0,1,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
1,0,0,0,0,0,1,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
2,0,0,0,0,0,1,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
3,0,0,0,0,0,1,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
4,0,0,0,0,0,1,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5855,0,0,0,0,0,1,0,0,1,1,...,0,0,0,1,0,0,0,0,1,0
5856,0,0,0,0,0,1,0,0,1,1,...,0,0,0,1,0,0,0,0,1,0
5857,0,0,0,0,0,1,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
5858,0,0,0,0,0,1,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
5859,0,0,0,0,0,1,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0

In [115]:
X.select_dtypes(include=["bool"])

,MS Zoning_A (agr),MS Zoning_C (all),MS Zoning_FV,MS Zoning_I (all),MS Zoning_RH,MS Zoning_RL,MS Zoning_RM,Street_Grvl,Street_Pave,Lot Shape_IR1,...,Sale Type_New,Sale Type_Oth,Sale Type_VWD,Sale Type_WD,Sale Condition_Abnorml,Sale Condition_AdjLand,Sale Condition_Alloca,Sale Condition_Family,Sale Condition_Normal,Sale Condition_Partial
0,False,False,False,False,False,True,False,False,True,False,...,False,False,False,True,False,False,False,False,True,False
1,False,False,False,False,False,True,False,False,True,False,...,False,False,False,True,False,False,False,False,True,False
2,False,False,False,False,False,True,False,False,True,False,...,False,False,False,True,False,False,False,False,True,False
3,False,False,False,False,False,True,False,False,True,False,...,False,False,False,True,False,False,False,False,True,False
4,False,False,False,False,False,True,False,False,True,False,...,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5855,False,False,False,False,False,True,False,False,True,True,...,False,False,False,True,False,False,False,False,True,False
5856,False,False,False,False,False,True,False,False,True,True,...,False,False,False,True,False,False,False,False,True,False
5857,False,False,False,False,False,True,False,False,True,False,...,False,False,False,True,False,False,False,False,True,False
5858,False,False,False,False,False,True,False,False,True,False,...,False,False,False,True,False,False,False,False,True,False
5859,False,False,False,False,False,True,False,False,True,False,...,False,False,False,True,False,False,False,False,True,False

In [ ]:
X_non_num.dtypes.value_counts()

int64    256
Name: count, dtype: int64

In [63]:
X_numeric = X.select_dtypes(include=['int64', 'float64'])

print("Any NaNs? ", X_numeric.isnull().any().any())
print("Any +inf? ", np.isinf(X_numeric).any().any())
print("Any -inf? ", np.isneginf(X_numeric).any().any())

Any NaNs?  False
Any +inf?  False
Any -inf?  False

In [49]:
np.isinf(X_numeric).sum()[np.isinf(X_numeric).sum() > 0]

Series([], dtype: int64)

In [50]:
np.isinf(X_numeric['bath per bedroom']).sum()

np.int64(0)

In [65]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [66]:
X

array([[-2.44865388, -0.61404139, -1.10944173, ..., -1.86623618,
        -1.62456175,  0.68917713],
       [-2.44698188, -0.6137368 , -1.10944173, ..., -1.86623618,
        -0.73135078,  0.64255736],
       [-2.44530987, -0.61373076, -1.10944173, ..., -0.80364932,
        -0.73135078,  0.78241669],
       ...,
       [ 0.        , -0.55707664, -0.12162307, ...,  0.25893755,
        -0.06144255, -0.05673929],
       [ 0.        , -0.55707664, -0.12162307, ...,  0.25893755,
        -0.06144255, -0.05673929],
       [ 0.        , -0.55707664, -0.12162307, ...,  0.25893755,
        -0.06144255, -0.05673929]], shape=(5860, 42))

In [123]:
def convert_bool_to_int(data: pd.DataFrame):
    print(data.shape)
    data_only_bool = data.select_dtypes(include= ["bool"])
    print("after slicing bool ", data_only_bool.shape)
    data_only_bool = data_only_bool.astype("int64")
    print("Converted boolean columns into int columns")
    return pd.concat([data.select_dtypes(exclude=['bool']), data_only_bool], axis= 1)

In [132]:
new_df = convert_bool_to_int(X)

(5860, 298)
after slicing bool  (5860, 256)
Converted boolean columns into int columns

Sale Condition_AdjLand  Sale Condition_Alloca  Sale Condition_Family  Sale Condition_Normal  Sale Condition_Partial
0                       0                      0                      1                      0                         5343
                                                                      0                      1                          245
                                                                                             0                          190
                                               1                      0                      0                           46
                        1                      0                      0                      0                           24
1                       0                      0                      0                      0                           12
Name: count, dtype: int64

In [176]:
def load_data(file_path):
    try:
        data = pd.read_csv(file_path)
        print(f"Data loaded: {data.shape[0]} rows, {data.shape[1]} columns")
        return data
    except FileNotFoundError:
        print(f'File now found on path: {file_path}')
        return None

def remove_null_columns(data: pd.DataFrame, threshold = 0.9):
    null_mean = data.isnull().mean()
    drop_null_index = null_mean[null_mean > threshold].index
    data.drop(columns = drop_null_index, inplace = True)
    print(f"Dropped {len(drop_null_index)} columns with missing values > {threshold*100}%")
    return data

def handling_inf_values(data: pd.DataFrame):
    # take the numeric data from dataframer
    num_data = data.select_dtypes(include=['int64', 'float64']).copy()
    num_data = num_data.replace([np.inf, -np.inf], np.nan)
    return pd.concat([num_data, data.select_dtypes(exclude=['int64', 'float64'])], axis= 1)

def convert_bool_to_int(data: pd.DataFrame):
    data_only_bool = data.select_dtypes(include= ["bool"])
    data_only_bool = data_only_bool.astype("int64")
    print("Converted boolean columns into int columns")
    df = pd.concat([data.select_dtypes(exclude=['bool']), data_only_bool], axis= 1)
    return df

def filling_missing_values(data: pd.DataFrame):
    for col in data.columns:
        # check if the column has null records or not
        if data[col].isnull().sum() > 0:
            # check is it is catogerical or numerical:
            if data[col].dtype == 'object':
                # if it is categorical, fill with mode
                data[col] = data[col].fillna(data[col].mode()[0])
            else:
                # if it is numerical, fill with median
                data[col] = data[col].fillna(data[col].median())
    print("Missing values are filled (media for numerical and mode for categorical)")
    return data


def save_data(data: pd.DataFrame, file_path):
    data.to_csv(file_path, index = False)
    print(f"cleaned data saved to: {file_path}")
    print(f"Data saved: {data.shape[0]} rows, {data.shape[1]} columns")

In [168]:
import pandas as pd
# from src import data_wrangling

def adding_features(dataFrame):
    #adding engineered features to the dataset
    # 1. adding total square foot of house
    dataFrame['Total SF'] = dataFrame['1st Flr SF'] + dataFrame['2nd Flr SF'] + dataFrame['Total Bsmt SF']
    # 2. adding total number of bedrooms
    dataFrame['Total Bathrooms'] = dataFrame['Full Bath'] + 0.5 * dataFrame['Half Bath']
    # Bathroom per bedrooms
    dataFrame['bath per bedroom'] = dataFrame['Total Bathrooms'] / dataFrame['Bedroom AbvGr']
    # 4. House age
    dataFrame['House Age'] = dataFrame['Yr Sold'] - dataFrame['Year Built']

    print(f"Added new engineered features: total SF (total sq. feet), total bathrooms, bathroom per bedroom, house age")
    return dataFrame
def save_engineered_dataFrame(data, save_path):
    data.to_csv(save_path, index=False)
    print(f'saved the dataset with new features at {save_path}')
    print(f'dimention of dataframe after feature engineering, {data.shape[0]} rows and {data.shape[1]}')

In [156]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

def load_data(cleaned_file_path):
    data = pd.read_csv(cleaned_file_path)
    print(f"data loaded for scaling. {data.shape[0]} rows and {data.shape[1]} columns loaded")
    return data

def one_hot_encode_cat(X_dataFrame:pd.DataFrame):
    encode_cat = pd.get_dummies(X_dataFrame)
    print("One Hot Encoding done for Cat columns.")
    return encode_cat

def scaling_num(X_dataFrame:pd.DataFrame):
    scaler = StandardScaler()
    X_dataFrame_num = X_dataFrame.select_dtypes(include=['int64', 'float64'])
    X_dataFrame_ex_num = X_dataFrame.select_dtypes(exclude=['int64', 'float64'])
    X_dataFrame_num = pd.DataFrame(scaler.fit_transform(X_dataFrame_num), columns= X_dataFrame_num.columns)
    df = pd.concat([X_dataFrame_num, X_dataFrame_ex_num], axis= 1)
    print("Scaling for Num Columns completed.")
    return df

def save_data(dataFrame:pd.DataFrame, dest_file_path):
    dataFrame.to_csv(dest_file_path, index=False)
    print(f"Refined Dataframe saved to {dest_file_path}")

In [155]:
def run_data_wrangling(raw_path= "data/raw/AmesHousing.csv", cleaned_path= "data/processed/Clean_AmesHousing.csv"):
    print("------------ Data Wrangling Started ------------")
    df = load_data(raw_path)
    if df is not None:
        df = remove_null_columns(df)
        df = handling_inf_values(df)
        df = filling_missing_values(df)
        # df = convert_bool_to_int(df)
        save_data(df, cleaned_path)
    print("------------- Data Wrangling Finished ------------")

In [165]:
def run_feature_engineering(origin_path, dest_path):
    # load the data
    print("---------- Feature Engineernig ----------")
    data = load_data(origin_path) # taking load data method from data_wrangling module
    new_data = adding_features(data)
    # save the data
    save_engineered_dataFrame(new_data, dest_path)
    print("---------- Feature Engineernig Done ----------")

In [180]:
def runScaling_features(dataFrame:pd.DataFrame, pred_cols_df:pd.DataFrame):
    # making X and y from the dataset
    X = dataFrame.drop(columns=pred_cols_df.columns)
    y = pred_cols_df

    # scaling categorical columns
    X = one_hot_encode_cat(X)

    # handling inf values
    X = handling_inf_values(X)
    
    # scaling number columns
    X = scaling_num(X)

    # convert bool into int
    X = convert_bool_to_int(X)

    # df = X.merge(y)    
    df = pd.concat([pd.DataFrame(X) , y], axis= 1)

    return df

In [160]:
raw_path= "../data/raw/AmesHousing.csv"
cleaned_path= "../data/processed/test_Clean_AmesHousing.csv"
scaled_path= "../data/processed/test_Clean_Scaled_AmesHousing.csv"

In [161]:
run_data_wrangling(raw_path= raw_path, cleaned_path= cleaned_path)

------------ Data Wrangling Started ------------
data loaded for scaling. 2930 rows and 82 columns loaded
Dropped 3 columns with missing values > 90.0%
Missing values are filled (media for numerical and mode for categorical)
Refined Dataframe saved to ../data/processed/test_Clean_AmesHousing.csv
------------- Data Wrangling Finished ------------

In [169]:
run_feature_engineering(origin_path= raw_path, dest_path= cleaned_path)

---------- Feature Engineernig ----------
data loaded for scaling. 2930 rows and 82 columns loaded
Added new engineered features: total SF (total sq. feet), total bathrooms, bathroom per bedroom, house age
saved the dataset with new features at ../data/processed/test_Clean_AmesHousing.csv
dimention of dataframe after feature engineering, 2930 rows and 86
---------- Feature Engineernig Done ----------

In [171]:
test_clean_path = "../data/processed/test_Clean_AmesHousing.csv"
test_clean_df = load_data(test_clean_path)
test_clean_df

data loaded for scaling. 2930 rows and 86 columns loaded

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice,Total SF,Total Bathrooms,bath per bedroom,House Age
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,5,2010,WD,Normal,215000,2736.0,1.0,0.333333,50
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,6,2010,WD,Normal,105000,1778.0,1.0,0.500000,49
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,12500,6,2010,WD,Normal,172000,2658.0,1.5,0.500000,52
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,4,2010,WD,Normal,244000,4220.0,2.5,0.833333,42
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,3,2010,WD,Normal,189900,2557.0,2.5,0.833333,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,2926,923275080,80,RL,37.0,7937,Pave,NaN,IR1,Lvl,...,0,3,2006,WD,Normal,142500,2006.0,1.0,0.333333,22
2926,2927,923276100,20,RL,NaN,8885,Pave,NaN,IR1,Low,...,0,6,2006,WD,Normal,131000,1766.0,1.0,0.500000,23
2927,2928,923400125,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,...,700,7,2006,WD,Normal,132000,1882.0,1.0,0.333333,14
2928,2929,924100070,20,RL,77.0,10010,Pave,NaN,Reg,Lvl,...,0,4,2006,WD,Normal,170000,2778.0,1.0,0.500000,32
2929,2930,924151050,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,...,0,11,2006,WD,Normal,188000,2996.0,2.5,0.833333,13

In [ ]:
runScaling_features(dataFrame=test_clean_df, pred_cols_df=test_clean_df[['SalePrice']])

One Hot Encoding done for Cat columns.
Scaling for Num Columns completed.
Converted boolean columns into int columns

,Order,PID,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,...,Sale Type_Oth,Sale Type_VWD,Sale Type_WD,Sale Condition_Abnorml,Sale Condition_AdjLand,Sale Condition_Alloca,Sale Condition_Family,Sale Condition_Normal,Sale Condition_Partial,SalePrice
0,-1.731460,-0.997164,-0.877005,3.072506,2.744381,-0.067254,-0.506718,-0.375537,-1.163488,0.056417,...,0,0,1,0,0,0,0,1,0,215000
1,-1.730277,-0.996904,-0.877005,0.461265,0.187097,-0.776079,0.393091,-0.342468,-1.115542,-0.568996,...,0,0,1,0,0,0,0,1,0,105000
2,-1.729095,-0.996899,-0.877005,0.504073,0.522814,-0.067254,0.393091,-0.441674,-1.259380,0.034081,...,0,0,1,0,0,0,0,1,0,172000
3,-1.727913,-0.996888,-0.877005,1.017759,0.128458,0.641571,-0.506718,-0.110988,-0.779919,-0.568996,...,0,0,1,0,0,0,0,1,0,244000
4,-1.726731,-0.992903,0.061285,0.204422,0.467348,-0.776079,-0.506718,0.848000,0.658466,-0.568996,...,0,0,1,0,0,0,0,1,0,189900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,1.726731,1.106582,0.530430,-1.379445,-0.280621,-0.067254,0.393091,0.418109,-0.012780,-0.568996,...,0,0,1,0,0,0,0,1,0,142500
2926,1.727913,1.106588,-0.877005,NaN,-0.160296,-0.776079,-0.506718,0.385040,-0.060726,-0.568996,...,0,0,1,0,0,0,0,1,0,131000
2927,1.729095,1.107245,0.647716,-0.309265,0.037199,-0.776079,-0.506718,0.682657,0.370789,-0.568996,...,0,0,1,0,0,0,0,1,0,132000
2928,1.730277,1.110954,-0.877005,0.332844,-0.017506,-0.776079,-0.506718,0.087423,-0.444296,-0.568996,...,0,0,1,0,0,0,0,1,0,170000
2929,1.731460,1.111225,0.061285,0.204422,-0.066118,0.641571,-0.506718,0.715726,0.466681,-0.044096,...,0,0,1,0,0,0,0,1,0,188000

:

In [7]:
import pandas as pd
import joblib
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.model_selection import train_test_split

def import_data(path = "../data/processed/Clean_AmesHousing.csv"):
    # import the data
    data = pd.read_csv(path)
    return data

def run_model(model_path= "../models/randomForest_tunned.pkl", clean_file_path = "../data/processed/Clean_AmesHousing.csv", target_col = "SalePrice"):
    data = import_data(clean_file_path)

    model = joblib.load(model_path)
    X = data.drop(columns= [target_col])
    y = data[target_col]
    # print(type(data), data.shape)
    # print(type(X), X.shape)
    # print(type(y), y.shape)
    X_train, y_train, X_test, y_test = train_test_split(X, y, train_size= 0.8, random_state= 42)

    print(type(X_test), X_test.shape)
    print(type(y_test), y_test.shape)
    # print(type(X_train), X_train.shape)
    # print(type(y_train), y_train.shape)
    y_pred = model.predict(X_test)

    results= {
        "MAE": mean_absolute_error(y_test, y_pred),
        "MSE": mean_squared_error(y_test, y_pred),
        "R2 Score": r2_score(y_test, y_pred)
    }

    return results

In [11]:
import_data().columns.to_list()

['Order',
 'PID',
 'MS SubClass',
 'Lot Frontage',
 'Lot Area',
 'Overall Qual',
 'Overall Cond',
 'Year Built',
 'Year Remod/Add',
 'Mas Vnr Area',
 'BsmtFin SF 1',
 'BsmtFin SF 2',
 'Bsmt Unf SF',
 'Total Bsmt SF',
 '1st Flr SF',
 '2nd Flr SF',
 'Low Qual Fin SF',
 'Gr Liv Area',
 'Bsmt Full Bath',
 'Bsmt Half Bath',
 'Full Bath',
 'Half Bath',
 'Bedroom AbvGr',
 'Kitchen AbvGr',
 'TotRms AbvGrd',
 'Fireplaces',
 'Garage Yr Blt',
 'Garage Cars',
 'Garage Area',
 'Wood Deck SF',
 'Open Porch SF',
 'Enclosed Porch',
 '3Ssn Porch',
 'Screen Porch',
 'Pool Area',
 'Misc Val',
 'Mo Sold',
 'Yr Sold',
 'Total SF',
 'Total Bathrooms',
 'bath per bedroom',
 'House Age',
 'MS Zoning_A (agr)',
 'MS Zoning_C (all)',
 'MS Zoning_FV',
 'MS Zoning_I (all)',
 'MS Zoning_RH',
 'MS Zoning_RL',
 'MS Zoning_RM',
 'Street_Grvl',
 'Street_Pave',
 'Lot Shape_IR1',
 'Lot Shape_IR2',
 'Lot Shape_IR3',
 'Lot Shape_Reg',
 'Land Contour_Bnk',
 'Land Contour_HLS',
 'Land Contour_Low',
 'Land Contour_Lvl',
 'Utilities_AllPub',
 'Utilities_NoSeWa',
 'Utilities_NoSewr',
 'Lot Config_Corner',
 'Lot Config_CulDSac',
 'Lot Config_FR2',
 'Lot Config_FR3',
 'Lot Config_Inside',
 'Land Slope_Gtl',
 'Land Slope_Mod',
 'Land Slope_Sev',
 'Neighborhood_Blmngtn',
 'Neighborhood_Blueste',
 'Neighborhood_BrDale',
 'Neighborhood_BrkSide',
 'Neighborhood_ClearCr',
 'Neighborhood_CollgCr',
 'Neighborhood_Crawfor',
 'Neighborhood_Edwards',
 'Neighborhood_Gilbert',
 'Neighborhood_Greens',
 'Neighborhood_GrnHill',
 'Neighborhood_IDOTRR',
 'Neighborhood_Landmrk',
 'Neighborhood_MeadowV',
 'Neighborhood_Mitchel',
 'Neighborhood_NAmes',
 'Neighborhood_NPkVill',
 'Neighborhood_NWAmes',
 'Neighborhood_NoRidge',
 'Neighborhood_NridgHt',
 'Neighborhood_OldTown',
 'Neighborhood_SWISU',
 'Neighborhood_Sawyer',
 'Neighborhood_SawyerW',
 'Neighborhood_Somerst',
 'Neighborhood_StoneBr',
 'Neighborhood_Timber',
 'Neighborhood_Veenker',
 'Condition 1_Artery',
 'Condition 1_Feedr',
 'Condition 1_Norm',
 'Condition 1_PosA',
 'Condition 1_PosN',
 'Condition 1_RRAe',
 'Condition 1_RRAn',
 'Condition 1_RRNe',
 'Condition 1_RRNn',
 'Condition 2_Artery',
 'Condition 2_Feedr',
 'Condition 2_Norm',
 'Condition 2_PosA',
 'Condition 2_PosN',
 'Condition 2_RRAe',
 'Condition 2_RRAn',
 'Condition 2_RRNn',
 'Bldg Type_1Fam',
 'Bldg Type_2fmCon',
 'Bldg Type_Duplex',
 'Bldg Type_Twnhs',
 'Bldg Type_TwnhsE',
 'House Style_1.5Fin',
 'House Style_1.5Unf',
 'House Style_1Story',
 'House Style_2.5Fin',
 'House Style_2.5Unf',
 'House Style_2Story',
 'House Style_SFoyer',
 'House Style_SLvl',
 'Roof Style_Flat',
 'Roof Style_Gable',
 'Roof Style_Gambrel',
 'Roof Style_Hip',
 'Roof Style_Mansard',
 'Roof Style_Shed',
 'Roof Matl_ClyTile',
 'Roof Matl_CompShg',
 'Roof Matl_Membran',
 'Roof Matl_Metal',
 'Roof Matl_Roll',
 'Roof Matl_Tar&Grv',
 'Roof Matl_WdShake',
 'Roof Matl_WdShngl',
 'Exterior 1st_AsbShng',
 'Exterior 1st_AsphShn',
 'Exterior 1st_BrkComm',
 'Exterior 1st_BrkFace',
 'Exterior 1st_CBlock',
 'Exterior 1st_CemntBd',
 'Exterior 1st_HdBoard',
 'Exterior 1st_ImStucc',
 'Exterior 1st_MetalSd',
 'Exterior 1st_Plywood',
 'Exterior 1st_PreCast',
 'Exterior 1st_Stone',
 'Exterior 1st_Stucco',
 'Exterior 1st_VinylSd',
 'Exterior 1st_Wd Sdng',
 'Exterior 1st_WdShing',
 'Exterior 2nd_AsbShng',
 'Exterior 2nd_AsphShn',
 'Exterior 2nd_Brk Cmn',
 'Exterior 2nd_BrkFace',
 'Exterior 2nd_CBlock',
 'Exterior 2nd_CmentBd',
 'Exterior 2nd_HdBoard',
 'Exterior 2nd_ImStucc',
 'Exterior 2nd_MetalSd',
 'Exterior 2nd_Other',
 'Exterior 2nd_Plywood',
 'Exterior 2nd_PreCast',
 'Exterior 2nd_Stone',
 'Exterior 2nd_Stucco',
 'Exterior 2nd_VinylSd',
 'Exterior 2nd_Wd Sdng',
 'Exterior 2nd_Wd Shng',
 'Mas Vnr Type_BrkCmn',
 'Mas Vnr Type_BrkFace',
 'Mas Vnr Type_CBlock',
 'Mas Vnr Type_Stone',
 'Exter Qual_Ex',
 'Exter Qual_Fa',
 'Exter Qual_Gd',
 'Exter Qual_TA',
 'Exter Cond_Ex',
 'Exter Cond_Fa',
 'Exter Cond_Gd',
 'Exter Cond_Po',
 'Exter Cond_TA',
 'Foundation_BrkTil',
 'Foundation_CBlock',
 'Foundation_PConc',
 'Foundation_Slab',
 'Foundation_Stone',
 'Foundation_Wood',
 'Bsmt Qual_Ex',
 'Bsmt Qual_Fa',
 'Bsmt Qual_Gd',
 'Bsmt Qual_Po',
 'Bsmt Qual_TA',
 'Bsmt Cond_Ex',
 'Bsmt Cond_Fa',
 'Bsmt Cond_Gd',
 'Bsmt Cond_Po',
 'Bsmt Cond_TA',
 'Bsmt Exposure_Av',
 'Bsmt Exposure_Gd',
 'Bsmt Exposure_Mn',
 'Bsmt Exposure_No',
 'BsmtFin Type 1_ALQ',
 'BsmtFin Type 1_BLQ',
 'BsmtFin Type 1_GLQ',
 'BsmtFin Type 1_LwQ',
 'BsmtFin Type 1_Rec',
 'BsmtFin Type 1_Unf',
 'BsmtFin Type 2_ALQ',
 'BsmtFin Type 2_BLQ',
 'BsmtFin Type 2_GLQ',
 'BsmtFin Type 2_LwQ',
 'BsmtFin Type 2_Rec',
 'BsmtFin Type 2_Unf',
 'Heating_Floor',
 'Heating_GasA',
 'Heating_GasW',
 'Heating_Grav',
 'Heating_OthW',
 'Heating_Wall',
 'Heating QC_Ex',
 'Heating QC_Fa',
 'Heating QC_Gd',
 'Heating QC_Po',
 'Heating QC_TA',
 'Central Air_N',
 'Central Air_Y',
 'Electrical_FuseA',
 'Electrical_FuseF',
 'Electrical_FuseP',
 'Electrical_Mix',
 'Electrical_SBrkr',
 'Kitchen Qual_Ex',
 'Kitchen Qual_Fa',
 'Kitchen Qual_Gd',
 'Kitchen Qual_Po',
 'Kitchen Qual_TA',
 'Functional_Maj1',
 'Functional_Maj2',
 'Functional_Min1',
 'Functional_Min2',
 'Functional_Mod',
 'Functional_Sal',
 'Functional_Sev',
 'Functional_Typ',
 'Fireplace Qu_Ex',
 'Fireplace Qu_Fa',
 'Fireplace Qu_Gd',
 'Fireplace Qu_Po',
 'Fireplace Qu_TA',
 'Garage Type_2Types',
 'Garage Type_Attchd',
 'Garage Type_Basment',
 'Garage Type_BuiltIn',
 'Garage Type_CarPort',
 'Garage Type_Detchd',
 'Garage Finish_Fin',
 'Garage Finish_RFn',
 'Garage Finish_Unf',
 'Garage Qual_Ex',
 'Garage Qual_Fa',
 'Garage Qual_Gd',
 'Garage Qual_Po',
 'Garage Qual_TA',
 'Garage Cond_Ex',
 'Garage Cond_Fa',
 'Garage Cond_Gd',
 'Garage Cond_Po',
 'Garage Cond_TA',
 'Paved Drive_N',
 'Paved Drive_P',
 'Paved Drive_Y',
 'Fence_GdPrv',
 'Fence_GdWo',
 'Fence_MnPrv',
 'Fence_MnWw',
 'Sale Type_COD',
 'Sale Type_CWD',
 'Sale Type_Con',
 'Sale Type_ConLD',
 'Sale Type_ConLI',
 'Sale Type_ConLw',
 'Sale Type_New',
 'Sale Type_Oth',
 'Sale Type_VWD',
 'Sale Type_WD ',
 'Sale Condition_Abnorml',
 'Sale Condition_AdjLand',
 'Sale Condition_Alloca',
 'Sale Condition_Family',
 'Sale Condition_Normal',
 'Sale Condition_Partial',
 'SalePrice']

In [14]:
run_model()

<class 'pandas.core.series.Series'> (2344,)
<class 'pandas.core.series.Series'> (586,)

c:\Users\RUTVIK\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

In [152]:
uncleaned_file = load_data(raw_path)

data loaded for scaling. 2930 rows and 82 columns loaded

In [147]:
cleaned_file = load_data(cleaned_path)

data loaded for scaling. 5860 rows and 79 columns loaded

In [153]:
uncleaned_file.dtypes.value_counts()

object     43
int64      28
float64    11
Name: count, dtype: int64

In [151]:
cleaned_file.dtypes.value_counts()

object     40
float64    39
Name: count, dtype: int64

In [1]:
import pandas as pd

In [4]:
data = pd.read_csv('../data/processed/Clean_AmesHousing.csv')

In [5]:
data.isna().any()

Order                     False
PID                       False
MS SubClass               False
Lot Frontage               True
Lot Area                  False
                          ...
Sale Condition_Alloca     False
Sale Condition_Family     False
Sale Condition_Normal     False
Sale Condition_Partial    False
SalePrice                 False
Length: 310, dtype: bool

In [ ]:
import pandas as pd

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor

from sklearn.model_selection import train_test_split

from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

# import the data
data = pd.read_csv("../data/processed/Clean_AmesHousing.csv")

# making feature and target datasets
X = data.drop(columns='SalePrice')
y = data['SalePrice']

# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= 42)

# Preparing Models dictionary
models = {
    "Liner Regression": LinearRegression(),
    "Ridge Regression": Ridge(alpha= 1.0),
    "Lasso Regression": Lasso(alpha= 1.0),
    "Random Forest": RandomForestRegressor(n_estimators= 100, random_state= 42)
}

# evalution container
results = dict()

# training and evaluating each models
for model_name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    results[model_name] = {
        "MAE": mean_absolute_error(y_test, y_pred),
        "MSE": mean_squared_error(y_test, y_pred),
        "R2 Score": r2_score(y_test, y_pred)
    }

c:\Users\RUTVIK\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.323e+11, tolerance: 1.394e+09
  model = cd_fast.enet_coordinate_descent(

In [7]:
pd.DataFrame(results).T

                           MAE           MSE  R2 Score
Liner Regression  16370.090177  8.567883e+08  0.893136
Ridge Regression  16509.413893  8.464369e+08  0.894427
Lasso Regression  16266.603966  8.438709e+08  0.894747
Random Forest     15495.733242  6.234266e+08  0.922242

Here we can see that Random forest is the best choice for the price prediction

In [2]:
import pandas as pd

from sklearn.ensemble import RandomForestRegressor

from sklearn.model_selection import train_test_split

from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

# import the data
data = pd.read_csv("../data/processed/Clean_AmesHousing.csv")

# making feature and target datasets
X = data.drop(columns='SalePrice')
y = data['SalePrice']

# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= 42)

# Preparing Model
model_rf = RandomForestRegressor(n_estimators= 100, random_state= 42)
model_rf.fit(X_train, y_train)
y_pred = model_rf.predict(X_test)

# Evalute model
results_rf = {
        "MAE": mean_absolute_error(y_test, y_pred),
        "MSE": mean_squared_error(y_test, y_pred),
        "R2 Score": r2_score(y_test, y_pred)
    }

results_rf

{'MAE': 15495.733242320819,
 'MSE': 623426568.7779055,
 'R2 Score': 0.9222422398780321}

In [ ]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid for Grid Search
param_grid = {
    'n_estimators': [100, 200],            # Number of trees
    'max_depth': [10, 20, None],           # Depth of each tree
    'min_samples_split': [2, 5],           # Minimum samples to split a node
    'min_samples_leaf': [1, 2],            # Minimum samples at a leaf
    'max_features': ['sqrt', 'log2'],      # Number of features to consider at each split
    'bootstrap': [True]                    # Use bootstrapped samples
}

# Preparing Models dictionary
model_rf = RandomForestRegressor(random_state= 42)

# Instantiate GridSearchCV
grid_search = GridSearchCV(estimator=model_rf,
                           param_grid=param_grid,
                           cv=5,                   # 5-fold cross-validation
                           n_jobs=-1,              # Use all cores
                           scoring='r2',           # Use RÂ² score
                           verbose=1)

# Fit the model
grid_search.fit(X_train, y_train)

# Print the best parameters and best score
print("Best Parameters:", grid_search.best_params_)
print("Best RÂ² Score:", grid_search.best_score_)

Fitting 5 folds for each of 48 candidates, totalling 240 fits
Best Parameters: {'bootstrap': True, 'max_depth': None, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}
Best RÂ² Score: 0.8831600634386808

In [32]:
import pandas as pd
y= import_data(path= "../data/train/y_train.csv")
type(y[y.columns.to_list()[0]])
y= y[y.columns.to_list()[0]].to_frame(name= "Acutual_Sales_Price")
y

      Acutual_Sales_Price
0                  152000
1                  185000
2                  101800
3                   90000
4                   94550
...                   ...
2339               155000
2340               176000
2341               207500
2342               122250
2343               133900

[2344 rows x 1 columns]

In [41]:
import pandas as pd

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

# from sklearn.model_selection import train_test_split

from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

import joblib

def import_data(path = "data/processed/Clean_AmesHousing.csv"):
    # import the data
    data = pd.read_csv(path)
    return data

def create_model(X_path= "data/train/X_train.csv", y_path= "data/train/y_train.csv"):
    # data = import_data(path)
    # making feature and target datasets
    X = import_data(X_path)
    y = import_data(y_path)
    y = y[y.columns.to_list()[0]]

    # train test split
    # X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= 42)

    # Define the parameter grid
    param_grid = {
        'n_estimators': [100, 200],            # Number of trees
        'max_depth': [10, 20, None],           # Depth of each tree
        'min_samples_split': [2, 5],           # Minimum samples to split a node
        'min_samples_leaf': [1, 2],            # Minimum samples at a leaf
        'max_features': ['sqrt', 'log2'],      # Number of features to consider at each split
        'bootstrap': [True]                    # Use bootstrapped samples
    }


    # Preparing Models dictionary
    model_rf = RandomForestRegressor(random_state= 42)

    # set up the grid
    grid_search = GridSearchCV(
        estimator=model_rf,
        param_grid=param_grid,
        cv=5,                                  # 5-fold cross-validation
        scoring='neg_root_mean_squared_error', # RMSE (lower = better)
        verbose=1,
        n_jobs=-1                              # Use all available CPU cores'
    )

    # fit grid on training data
    grid_search.fit(X, y)

    # get the best parameters
    print ("Best Parameteres:", grid_search.best_params_)
    print ("Best RMSE:", -grid_search.best_score_)

    # training models
    # # model_rf.fit(X_train, y_train)
    # # y_pred = model_rf.predict(X_test)

    model_rf_best = grid_search.best_estimator_
    model_rf_best.fit(X, y)
    # y_pred = model_rf_best.predict(X_test)

    # results= {
    #     "MAE": mean_absolute_error(y_test, y_pred),
    #     "MSE": mean_squared_error(y_test, y_pred),
    #     "R2 Score": r2_score(y_test, y_pred)
    # }

    # print(results)

    # save the model
    save_path = "../models/randomForest_tunned.pkl"
    joblib.dump(model_rf_best, save_path)
    print(f"Saved the model at {save_path}")

def run_model(model_path= "models/randomForest_tunned.pkl", X_test_file = "data/test/X_test.csv", y_test_path = None, target_col = "SalePrice"):
    X = import_data(X_test_file)

    model = joblib.load(model_path)
    
    y_pred = model.predict(X)
    print(type(y_pred))
    if y_test_path != None:
        y = import_data(y_test_path)
        y = y[target_col]
        res = y.to_frame(name= "Acutal_"+ target_col)
        res = pd.concat([X, res], join="inner")
        results= {
            "MAE": mean_absolute_error(y, y_pred),
            "MSE": mean_squared_error(y, y_pred),
            "R2 Score": r2_score(y, y_pred)
        }
        
        print (results)
    else:
        print("No testing for prediction...")

    res = pd.DataFrame(y_pred, columns= ["pred_"+target_col])
    res = pd.concat([X, res], join="inner")
    return res

if __name__ == "__main__":
    print("---------- Running Modeling Script ----------")
    X_path= "../data/train/X_train.csv"
    y_path= "../data/train/y_train.csv" 
    X_test_file = "../data/test/X_test.csv"
    y_test_path = "../data/test/y_test.csv"
    model_path = "../models/randomForest_tunned.pkl"
    
    create_model(X_path= X_path, y_path= y_path)
    run_model(model_path= model_path, X_test_file = X_test_file, y_test_path = y_test_path, target_col = "SalePrice")

---------- Running Modeling Script ----------
Fitting 5 folds for each of 48 candidates, totalling 240 fits
Best Parameteres: {'bootstrap': True, 'max_depth': None, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}
Best RMSE: 26248.89803319769
Saved the model at ../models/randomForest_tunned.pkl
<class 'numpy.ndarray'>
{'MAE': 15353.005981228667, 'MSE': 713793534.6943499, 'R2 Score': 0.9109710923033381}